# Generated by Django 3.0.7 on 2020-07-14 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('date_joined_alert', models.DateTimeField(auto_now_add=True, verbose_name='Date Subscribed')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_name', models.CharField(blank=True, max_length=200, verbose_name='Offer Name')),
                ('offer_type', models.CharField(blank=True, choices=[(None, 'Select Job Type'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], max_length=200, null=True, verbose_name='Offer Type')),
                ('offer_job_name', models.CharField(blank=True, default='Software Developer', max_length=200, null=True)),
                ('offer_number', models.IntegerField(blank=True, null=True, verbose_name='Offer number')),
                ('offer_description', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name')),
                ('company_description', models.TextField()),
                ('offer_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Offer Location')),
                ('offer_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('offer_status', models.IntegerField(blank=True, null=True, verbose_name='Offer Status')),
                ('offer_min_max_limit', models.IntegerField(blank=True, null=True, verbose_name='Offer Intake')),
                ('offer_date_created', models.DateTimeField(verbose_name='Offer Date')),
                ('offer_date_updated', models.DateTimeField(auto_now=True, verbose_name='Offer Date Updated')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='QuickContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Quick Contact',
            },
        ),
        migrations.CreateModel(
            name='UserResumeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(blank=True, max_length=200, null=True, upload_to='', verbose_name='User File Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('offer_id', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='offer_resume_user', related_query_name='offer_resume_user', to='offer.Offers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_user', related_query_name='real_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('user_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('request_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_offer_from_client', related_query_name='request_offer_from_client', to='offer.Offers')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('user_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('apply_job_date', models.DateTimeField(auto_now_add=True, verbose_name='Apply Job Date Time')),
                ('offer_selected_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_selected', related_query_name='offer_selected', to='offer.Offers')),
            ],
            options={
                'verbose_name_plural': 'Apply User Form',
            },
        ),
    ]
