# Generated by Django 3.0.7 on 2020-07-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20200724_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
