# Generated by Django 3.0.7 on 2020-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20200729_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='applied_offer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
