# Generated by Django 3.0.7 on 2020-07-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_applyform_applied_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNeeded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skills Required',
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='skills_qualified',
            field=models.ManyToManyField(related_name='skill_required', related_query_name='skill_required', to='offer.SkillNeeded'),
        ),
    ]
