# Generated by Django 3.0.7 on 2020-07-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20200729_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillneeded',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
