# Generated by Django 3.0.7 on 2020-07-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20200729_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='skills_qualified',
            new_name='skill_qualified_offer',
        ),
    ]
