# Generated by Django 3.0.7 on 2020-07-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_auto_20200729_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillneeded',
            old_name='skills',
            new_name='skill_name',
        ),
    ]
