# Generated by Django 3.0.7 on 2020-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20200730_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='skill_qualified_offer',
            field=models.ManyToManyField(to='offer.SkillNeeded'),
        ),
    ]
