# Generated by Django 3.0.7 on 2020-08-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_auto_20200731_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_tag',
            field=models.ManyToManyField(to='offer.Tags'),
        ),
    ]
