# Generated by Django 3.0.7 on 2020-08-03 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0012_auto_20200803_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyform',
            old_name='offer_selected_by_user',
            new_name='offer_selected',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='applied_offer',
        ),
        migrations.AddField(
            model_name='applyform',
            name='user_who_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
