# Generated by Django 3.0.7 on 2020-08-03 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offer', '0013_auto_20200803_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='user_who_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
