# Generated by Django 3.0.7 on 2020-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_auto_20200803_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='offer_selected',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
