# Generated by Django 3.0.7 on 2020-07-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200714_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_image.png', null=True, upload_to='profile_image/', verbose_name='Profile Image'),
        ),
    ]
