# Generated by Django 3.0.7 on 2020-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200715_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_image.png', null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
