# Generated by Django 3.0.7 on 2020-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200724_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='applied_offer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
