# Generated by Django 3.0.7 on 2020-07-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_applied_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='applied_offer',
        ),
    ]
